services:
  hugo-blog:
    image: hugomods/hugo:exts
    # command: server -D
    command: hugo server -D --ignoreCache
    volumes:
      - ./:/src
      - ./hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
