services:
  server:
    image: hugomods/hugo:exts
    # command: server -D
    command: hugo server --ignoreCache
    volumes:
      - ./:/src
      - ./hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313